/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_cards_K8055_K8055JNI */

#ifndef _Included_lib_cards_K8055_K8055JNI
#define _Included_lib_cards_K8055_K8055JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_cards_K8055_K8055JNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_cards_K8055_K8055JNI_test
  (JNIEnv *, jobject);

/*
 * Class:     lib_cards_K8055_K8055JNI
 * Method:    openDevice
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_cards_K8055_K8055JNI_openDevice
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_cards_K8055_K8055JNI
 * Method:    closeDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lib_cards_K8055_K8055JNI_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     lib_cards_K8055_K8055JNI
 * Method:    readAnalogChannel
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_cards_K8055_K8055JNI_readAnalogChannel
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
